/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AMCPart {
  'id' : string,
  'associatedComputerId' : [] | [string],
  'purchaseDate' : bigint,
  'associatedSectionId' : [] | [string],
  'partNumber' : string,
  'supplier' : string,
  'createdAt' : bigint,
  'partName' : string,
  'notes' : string,
  'warrantyExpiry' : [] | [bigint],
  'quantity' : bigint,
}
export interface Complaint {
  'id' : string,
  'status' : ComplaintStatus,
  'caseClearedDate' : [] | [bigint],
  'computerId' : [] | [string],
  'createdAt' : bigint,
  'spareTakenDate' : [] | [bigint],
  'unit' : string,
  'description' : string,
  'sparesTaken' : string,
  'extraCol1' : string,
  'extraCol2' : string,
  'sectionId' : [] | [string],
  'reportedBy' : string,
  'amcTeam' : string,
  'priority' : Priority,
  'caseAttendedDate' : [] | [bigint],
  'resolvedAt' : [] | [bigint],
  'unitSlNo' : string,
}
export type ComplaintStatus = { 'resolved' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export interface Computer {
  'id' : string,
  'ip1' : string,
  'ip2' : string,
  'status' : { 'active' : null } |
    { 'standby' : null } |
    { 'retired' : null },
  'model' : string,
  'amcCompany' : string,
  'datasheetBlob' : [] | [ExternalBlob],
  'monitorModel' : string,
  'purchaseDate' : bigint,
  'createdAt' : bigint,
  'currentUser' : string,
  'sectionId' : string,
  'serialNumber' : string,
  'notes' : string,
  'companyName' : string,
  'brand' : string,
  'amcEndDate' : bigint,
  'amcStartDate' : bigint,
  'remarks' : string,
  'seatNumber' : string,
  'monitorSerial' : string,
}
export type ExternalBlob = Uint8Array;
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface ProcessStockEntriesResult {
  'updated' : bigint,
  'addedToStandby' : bigint,
}
export interface Section {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'location' : string,
}
export interface StandbySystem {
  'id' : string,
  'status' : { 'available' : null } |
    { 'inUse' : null } |
    { 'retired' : null },
  'model' : string,
  'createdAt' : bigint,
  'assignedSectionId' : [] | [string],
  'serialNumber' : string,
  'notes' : string,
  'brand' : string,
  'condition' : { 'fair' : null } |
    { 'good' : null } |
    { 'poor' : null },
}
export interface StockEntry {
  'id' : string,
  'createdAt' : bigint,
  'slNo' : bigint,
  'monitorSlNo' : string,
  'cpuSlNo' : string,
  'amcExpiryDate' : bigint,
  'amcTeam' : string,
  'companyAndModel' : string,
  'amcStartDate' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface OtherDevice {
  'id' : string,
  'slNo' : bigint,
  'unitArticle' : string,
  'makeAndModel' : string,
  'serialNumber' : string,
  'section' : string,
  'ipAddress' : string,
  'workingStatus' : string,
  'remarks' : string,
  'createdAt' : bigint,
}
export interface Device {
  'id': string,
  'serialNumber': string,
  'deviceType': string,
  'makeAndModel': string,
  'companyName': string,
  'amcTeam': string,
  'amcStartDate': bigint,
  'amcExpiryDate': bigint,
  'assignedSeatId': string,
  'sectionId': string,
  'workingStatus': string,
  'ipAddress': string,
  'remarks': string,
  'previousSection': string,
  'dateMovedToStandby': bigint,
  'createdAt': bigint,
}
export interface Seat {
  'id': string,
  'sectionId': string,
  'seatNumber': string,
  'currentUser': string,
  'cpuSerial': string,
  'monitorSerial': string,
  'ip1': string,
  'ip2': string,
  'remarks': string,
  'createdAt': bigint,
}

export interface MovementLog {
  'id': string;
  'dateTime': bigint;
  'deviceType': string;
  'serialNumber': string;
  'action': string;
  'previousSection': string;
  'newSection': string;
  'triggeredFrom': string;
  'user': string;
  'remarks': string;
}
export interface StockImportRow {
  'slNo': bigint;
  'companyAndModel': string;
  'cpuSlNo': string;
  'monitorSlNo': string;
  'amcStartDate': bigint;
  'amcExpiryDate': bigint;
  'amcTeam': string;
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAMCPart' : ActorMethod<[AMCPart], undefined>,
  'createComplaint' : ActorMethod<[Complaint], undefined>,
  'createComputer' : ActorMethod<[Computer], undefined>,
  'createSection' : ActorMethod<[Section], undefined>,
  'createStandbySystem' : ActorMethod<[StandbySystem], undefined>,
  'createStockEntry' : ActorMethod<[StockEntry], undefined>,
  'deleteAMCPart' : ActorMethod<[string], undefined>,
  'deleteComplaint' : ActorMethod<[string], undefined>,
  'deleteComputer' : ActorMethod<[string], undefined>,
  'deleteSection' : ActorMethod<[string], undefined>,
  'deleteStandbySystem' : ActorMethod<[string], undefined>,
  'deleteStockEntry' : ActorMethod<[string], undefined>,
  'createOtherDevice' : ActorMethod<[OtherDevice], undefined>,
  'getAllOtherDevices' : ActorMethod<[], Array<OtherDevice>>,
  'updateOtherDevice' : ActorMethod<[OtherDevice], undefined>,
  'deleteOtherDevice' : ActorMethod<[string], undefined>,
  'getAMCPart' : ActorMethod<[string], [] | [AMCPart]>,
  'getAllAMCParts' : ActorMethod<[], Array<AMCPart>>,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getAllComputers' : ActorMethod<[], Array<Computer>>,
  'getAllSections' : ActorMethod<[], Array<Section>>,
  'getAllStandbySystems' : ActorMethod<[], Array<StandbySystem>>,
  'getAllStockEntries' : ActorMethod<[], Array<StockEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaint' : ActorMethod<[string], [] | [Complaint]>,
  'getComplaintsByComputer' : ActorMethod<[string], Array<Complaint>>,
  'getComplaintsBySection' : ActorMethod<[string], Array<Complaint>>,
  'getComplaintsByStatus' : ActorMethod<[ComplaintStatus], Array<Complaint>>,
  'getComputer' : ActorMethod<[string], [] | [Computer]>,
  'getComputersBySection' : ActorMethod<[string], Array<Computer>>,
  'getComputersWithExpiringAMC' : ActorMethod<[bigint], Array<Computer>>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalSeats' : bigint,
      'totalStandbyDevices' : bigint,
      'pendingComplaints' : bigint,
      'clearedComplaints' : bigint,
      'totalOtherDevices' : bigint,
      'totalDevices' : bigint,
    }
  >,
  'getExpiringAMCParts' : ActorMethod<[bigint], Array<AMCPart>>,
  'getSection' : ActorMethod<[string], [] | [Section]>,
  'getStandbySystem' : ActorMethod<[string], [] | [StandbySystem]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processStockEntries' : ActorMethod<[], ProcessStockEntriesResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAMCPart' : ActorMethod<[AMCPart], undefined>,
  'updateComplaint' : ActorMethod<[Complaint], undefined>,
  'updateComputer' : ActorMethod<[Computer], undefined>,
  'updateSection' : ActorMethod<[Section], undefined>,
  'updateStandbySystem' : ActorMethod<[StandbySystem], undefined>,
  'updateStockEntry' : ActorMethod<[StockEntry], undefined>,
  'createDevice': ActorMethod<[Device], undefined>,
  'getDevice': ActorMethod<[string], [] | [Device]>,
  'getAllDevices': ActorMethod<[], Array<Device>>,
  'updateDevice': ActorMethod<[Device], undefined>,
  'deleteDevice': ActorMethod<[string], undefined>,
  'createSeat': ActorMethod<[Seat], undefined>,
  'getSeat': ActorMethod<[string], [] | [Seat]>,
  'getAllSeats': ActorMethod<[], Array<Seat>>,
  'updateSeat': ActorMethod<[Seat], undefined>,
  'deleteSeat': ActorMethod<[string], undefined>,
  'createMovementLog': ActorMethod<[MovementLog], undefined>,
  'getAllMovementLogs': ActorMethod<[], Array<MovementLog>>,
  'importStockRow': ActorMethod<[StockImportRow], undefined>,
  'clearAllData': ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];