/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AMCPart = IDL.Record({
  'id' : IDL.Text,
  'associatedComputerId' : IDL.Opt(IDL.Text),
  'purchaseDate' : IDL.Int,
  'associatedSectionId' : IDL.Opt(IDL.Text),
  'partNumber' : IDL.Text,
  'supplier' : IDL.Text,
  'createdAt' : IDL.Int,
  'partName' : IDL.Text,
  'notes' : IDL.Text,
  'warrantyExpiry' : IDL.Opt(IDL.Int),
  'quantity' : IDL.Nat,
});
export const Complaint = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  }),
  'computerId' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'sectionId' : IDL.Opt(IDL.Text),
  'reportedBy' : IDL.Text,
  'priority' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  }),
  'resolvedAt' : IDL.Opt(IDL.Int),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Computer = IDL.Record({
  'id' : IDL.Text,
  'ip1' : IDL.Text,
  'ip2' : IDL.Text,
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'standby' : IDL.Null,
    'retired' : IDL.Null,
  }),
  'model' : IDL.Text,
  'datasheetBlob' : IDL.Opt(ExternalBlob),
  'monitorModel' : IDL.Text,
  'purchaseDate' : IDL.Int,
  'createdAt' : IDL.Int,
  'currentUser' : IDL.Text,
  'sectionId' : IDL.Text,
  'serialNumber' : IDL.Text,
  'notes' : IDL.Text,
  'brand' : IDL.Text,
  'amcEndDate' : IDL.Int,
  'amcStartDate' : IDL.Int,
  'remarks' : IDL.Text,
  'seatNumber' : IDL.Text,
  'monitorSerial' : IDL.Text,
});
export const Section = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const StandbySystem = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'available' : IDL.Null,
    'inUse' : IDL.Null,
    'retired' : IDL.Null,
  }),
  'model' : IDL.Text,
  'createdAt' : IDL.Int,
  'assignedSectionId' : IDL.Opt(IDL.Text),
  'serialNumber' : IDL.Text,
  'notes' : IDL.Text,
  'brand' : IDL.Text,
  'condition' : IDL.Variant({
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
  }),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAMCPart' : IDL.Func([AMCPart], [], []),
  'createComplaint' : IDL.Func([Complaint], [], []),
  'createComputer' : IDL.Func([Computer], [], []),
  'createSection' : IDL.Func([Section], [], []),
  'createStandbySystem' : IDL.Func([StandbySystem], [], []),
  'deleteAMCPart' : IDL.Func([IDL.Text], [], []),
  'deleteComplaint' : IDL.Func([IDL.Text], [], []),
  'deleteComputer' : IDL.Func([IDL.Text], [], []),
  'deleteSection' : IDL.Func([IDL.Text], [], []),
  'deleteStandbySystem' : IDL.Func([IDL.Text], [], []),
  'getAMCPart' : IDL.Func([IDL.Text], [IDL.Opt(AMCPart)], ['query']),
  'getAllAMCParts' : IDL.Func([], [IDL.Vec(AMCPart)], ['query']),
  'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
  'getAllComputers' : IDL.Func([], [IDL.Vec(Computer)], ['query']),
  'getAllSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
  'getAllStandbySystems' : IDL.Func([], [IDL.Vec(StandbySystem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaint' : IDL.Func([IDL.Text], [IDL.Opt(Complaint)], ['query']),
  'getComplaintsByComputer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getComplaintsBySection' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getComplaintsByStatus' : IDL.Func(
      [
        IDL.Variant({
          'resolved' : IDL.Null,
          'open' : IDL.Null,
          'inProgress' : IDL.Null,
        }),
      ],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'getComputer' : IDL.Func([IDL.Text], [IDL.Opt(Computer)], ['query']),
  'getComputersBySection' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Computer)],
      ['query'],
    ),
  'getComputersWithExpiringAMC' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(Computer)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalStandbySystems' : IDL.Nat,
          'totalComputers' : IDL.Nat,
          'computersWithExpiringAMC' : IDL.Nat,
          'openComplaints' : IDL.Nat,
          'totalSections' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getExpiringAMCParts' : IDL.Func([IDL.Int], [IDL.Vec(AMCPart)], ['query']),
  'getSection' : IDL.Func([IDL.Text], [IDL.Opt(Section)], ['query']),
  'getStandbySystem' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StandbySystem)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAMCPart' : IDL.Func([AMCPart], [], []),
  'updateComplaint' : IDL.Func([Complaint], [], []),
  'updateComputer' : IDL.Func([Computer], [], []),
  'updateSection' : IDL.Func([Section], [], []),
  'updateStandbySystem' : IDL.Func([StandbySystem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AMCPart = IDL.Record({
    'id' : IDL.Text,
    'associatedComputerId' : IDL.Opt(IDL.Text),
    'purchaseDate' : IDL.Int,
    'associatedSectionId' : IDL.Opt(IDL.Text),
    'partNumber' : IDL.Text,
    'supplier' : IDL.Text,
    'createdAt' : IDL.Int,
    'partName' : IDL.Text,
    'notes' : IDL.Text,
    'warrantyExpiry' : IDL.Opt(IDL.Int),
    'quantity' : IDL.Nat,
  });
  const Complaint = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'resolved' : IDL.Null,
      'open' : IDL.Null,
      'inProgress' : IDL.Null,
    }),
    'computerId' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'sectionId' : IDL.Opt(IDL.Text),
    'reportedBy' : IDL.Text,
    'priority' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'medium' : IDL.Null,
    }),
    'resolvedAt' : IDL.Opt(IDL.Int),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Computer = IDL.Record({
    'id' : IDL.Text,
    'ip1' : IDL.Text,
    'ip2' : IDL.Text,
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'standby' : IDL.Null,
      'retired' : IDL.Null,
    }),
    'model' : IDL.Text,
    'datasheetBlob' : IDL.Opt(ExternalBlob),
    'monitorModel' : IDL.Text,
    'purchaseDate' : IDL.Int,
    'createdAt' : IDL.Int,
    'currentUser' : IDL.Text,
    'sectionId' : IDL.Text,
    'serialNumber' : IDL.Text,
    'notes' : IDL.Text,
    'brand' : IDL.Text,
    'amcEndDate' : IDL.Int,
    'amcStartDate' : IDL.Int,
    'remarks' : IDL.Text,
    'seatNumber' : IDL.Text,
    'monitorSerial' : IDL.Text,
  });
  const Section = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const StandbySystem = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'available' : IDL.Null,
      'inUse' : IDL.Null,
      'retired' : IDL.Null,
    }),
    'model' : IDL.Text,
    'createdAt' : IDL.Int,
    'assignedSectionId' : IDL.Opt(IDL.Text),
    'serialNumber' : IDL.Text,
    'notes' : IDL.Text,
    'brand' : IDL.Text,
    'condition' : IDL.Variant({
      'fair' : IDL.Null,
      'good' : IDL.Null,
      'poor' : IDL.Null,
    }),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAMCPart' : IDL.Func([AMCPart], [], []),
    'createComplaint' : IDL.Func([Complaint], [], []),
    'createComputer' : IDL.Func([Computer], [], []),
    'createSection' : IDL.Func([Section], [], []),
    'createStandbySystem' : IDL.Func([StandbySystem], [], []),
    'deleteAMCPart' : IDL.Func([IDL.Text], [], []),
    'deleteComplaint' : IDL.Func([IDL.Text], [], []),
    'deleteComputer' : IDL.Func([IDL.Text], [], []),
    'deleteSection' : IDL.Func([IDL.Text], [], []),
    'deleteStandbySystem' : IDL.Func([IDL.Text], [], []),
    'getAMCPart' : IDL.Func([IDL.Text], [IDL.Opt(AMCPart)], ['query']),
    'getAllAMCParts' : IDL.Func([], [IDL.Vec(AMCPart)], ['query']),
    'getAllComplaints' : IDL.Func([], [IDL.Vec(Complaint)], ['query']),
    'getAllComputers' : IDL.Func([], [IDL.Vec(Computer)], ['query']),
    'getAllSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
    'getAllStandbySystems' : IDL.Func([], [IDL.Vec(StandbySystem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaint' : IDL.Func([IDL.Text], [IDL.Opt(Complaint)], ['query']),
    'getComplaintsByComputer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getComplaintsBySection' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getComplaintsByStatus' : IDL.Func(
        [
          IDL.Variant({
            'resolved' : IDL.Null,
            'open' : IDL.Null,
            'inProgress' : IDL.Null,
          }),
        ],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'getComputer' : IDL.Func([IDL.Text], [IDL.Opt(Computer)], ['query']),
    'getComputersBySection' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Computer)],
        ['query'],
      ),
    'getComputersWithExpiringAMC' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(Computer)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalStandbySystems' : IDL.Nat,
            'totalComputers' : IDL.Nat,
            'computersWithExpiringAMC' : IDL.Nat,
            'openComplaints' : IDL.Nat,
            'totalSections' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getExpiringAMCParts' : IDL.Func([IDL.Int], [IDL.Vec(AMCPart)], ['query']),
    'getSection' : IDL.Func([IDL.Text], [IDL.Opt(Section)], ['query']),
    'getStandbySystem' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StandbySystem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAMCPart' : IDL.Func([AMCPart], [], []),
    'updateComplaint' : IDL.Func([Complaint], [], []),
    'updateComputer' : IDL.Func([Computer], [], []),
    'updateSection' : IDL.Func([Section], [], []),
    'updateStandbySystem' : IDL.Func([StandbySystem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };