/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AMCPart {
  'id' : string,
  'associatedComputerId' : [] | [string],
  'purchaseDate' : bigint,
  'associatedSectionId' : [] | [string],
  'partNumber' : string,
  'supplier' : string,
  'createdAt' : bigint,
  'partName' : string,
  'notes' : string,
  'warrantyExpiry' : [] | [bigint],
  'quantity' : bigint,
}
export interface Complaint {
  'id' : string,
  'status' : { 'resolved' : null } |
    { 'open' : null } |
    { 'inProgress' : null },
  'computerId' : [] | [string],
  'createdAt' : bigint,
  'description' : string,
  'sectionId' : [] | [string],
  'reportedBy' : string,
  'priority' : { 'low' : null } |
    { 'high' : null } |
    { 'medium' : null },
  'resolvedAt' : [] | [bigint],
}
export interface Computer {
  'id' : string,
  'ip1' : string,
  'ip2' : string,
  'status' : { 'active' : null } |
    { 'standby' : null } |
    { 'retired' : null },
  'model' : string,
  'datasheetBlob' : [] | [ExternalBlob],
  'monitorModel' : string,
  'purchaseDate' : bigint,
  'createdAt' : bigint,
  'currentUser' : string,
  'sectionId' : string,
  'serialNumber' : string,
  'notes' : string,
  'brand' : string,
  'amcEndDate' : bigint,
  'amcStartDate' : bigint,
  'remarks' : string,
  'seatNumber' : string,
  'monitorSerial' : string,
}
export type ExternalBlob = Uint8Array;
export interface Section {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'location' : string,
}
export interface StandbySystem {
  'id' : string,
  'status' : { 'available' : null } |
    { 'inUse' : null } |
    { 'retired' : null },
  'model' : string,
  'createdAt' : bigint,
  'assignedSectionId' : [] | [string],
  'serialNumber' : string,
  'notes' : string,
  'brand' : string,
  'condition' : { 'fair' : null } |
    { 'good' : null } |
    { 'poor' : null },
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAMCPart' : ActorMethod<[AMCPart], undefined>,
  'createComplaint' : ActorMethod<[Complaint], undefined>,
  'createComputer' : ActorMethod<[Computer], undefined>,
  'createSection' : ActorMethod<[Section], undefined>,
  'createStandbySystem' : ActorMethod<[StandbySystem], undefined>,
  'deleteAMCPart' : ActorMethod<[string], undefined>,
  'deleteComplaint' : ActorMethod<[string], undefined>,
  'deleteComputer' : ActorMethod<[string], undefined>,
  'deleteSection' : ActorMethod<[string], undefined>,
  'deleteStandbySystem' : ActorMethod<[string], undefined>,
  'getAMCPart' : ActorMethod<[string], [] | [AMCPart]>,
  'getAllAMCParts' : ActorMethod<[], Array<AMCPart>>,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getAllComputers' : ActorMethod<[], Array<Computer>>,
  'getAllSections' : ActorMethod<[], Array<Section>>,
  'getAllStandbySystems' : ActorMethod<[], Array<StandbySystem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaint' : ActorMethod<[string], [] | [Complaint]>,
  'getComplaintsByComputer' : ActorMethod<[string], Array<Complaint>>,
  'getComplaintsBySection' : ActorMethod<[string], Array<Complaint>>,
  'getComplaintsByStatus' : ActorMethod<
    [{ 'resolved' : null } | { 'open' : null } | { 'inProgress' : null }],
    Array<Complaint>
  >,
  'getComputer' : ActorMethod<[string], [] | [Computer]>,
  'getComputersBySection' : ActorMethod<[string], Array<Computer>>,
  'getComputersWithExpiringAMC' : ActorMethod<[bigint], Array<Computer>>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalStandbySystems' : bigint,
      'totalComputers' : bigint,
      'computersWithExpiringAMC' : bigint,
      'openComplaints' : bigint,
      'totalSections' : bigint,
    }
  >,
  'getExpiringAMCParts' : ActorMethod<[bigint], Array<AMCPart>>,
  'getSection' : ActorMethod<[string], [] | [Section]>,
  'getStandbySystem' : ActorMethod<[string], [] | [StandbySystem]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAMCPart' : ActorMethod<[AMCPart], undefined>,
  'updateComplaint' : ActorMethod<[Complaint], undefined>,
  'updateComputer' : ActorMethod<[Computer], undefined>,
  'updateSection' : ActorMethod<[Section], undefined>,
  'updateStandbySystem' : ActorMethod<[StandbySystem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];