/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AMCPart {
    id: string;
    associatedComputerId?: string;
    purchaseDate: bigint;
    associatedSectionId?: string;
    partNumber: string;
    supplier: string;
    createdAt: bigint;
    partName: string;
    notes: string;
    warrantyExpiry?: bigint;
    quantity: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface StandbySystem {
    id: string;
    status: Variant_available_inUse_retired;
    model: string;
    createdAt: bigint;
    assignedSectionId?: string;
    serialNumber: string;
    notes: string;
    brand: string;
    condition: Variant_fair_good_poor;
}
export interface Complaint {
    id: string;
    status: Variant_resolved_open_inProgress;
    computerId?: string;
    createdAt: bigint;
    description: string;
    sectionId?: string;
    reportedBy: string;
    priority: Variant_low_high_medium;
    resolvedAt?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Section {
    id: string;
    name: string;
    createdAt: bigint;
    description: string;
    location: string;
}
export interface Computer {
    id: string;
    status: Variant_active_standby_retired;
    model: string;
    datasheetBlob?: ExternalBlob;
    purchaseDate: bigint;
    createdAt: bigint;
    currentUser: string;
    sectionId: string;
    serialNumber: string;
    notes: string;
    brand: string;
    amcEndDate: bigint;
    amcStartDate: bigint;
    seatNumber: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_standby_retired {
    active = "active",
    standby = "standby",
    retired = "retired"
}
export enum Variant_available_inUse_retired {
    available = "available",
    inUse = "inUse",
    retired = "retired"
}
export enum Variant_fair_good_poor {
    fair = "fair",
    good = "good",
    poor = "poor"
}
export enum Variant_low_high_medium {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Variant_resolved_open_inProgress {
    resolved = "resolved",
    open = "open",
    inProgress = "inProgress"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAMCPart(part: AMCPart): Promise<void>;
    createComplaint(complaint: Complaint): Promise<void>;
    createComputer(computer: Computer): Promise<void>;
    createSection(section: Section): Promise<void>;
    createStandbySystem(standbySystem: StandbySystem): Promise<void>;
    deleteAMCPart(id: string): Promise<void>;
    deleteComplaint(id: string): Promise<void>;
    deleteComputer(id: string): Promise<void>;
    deleteSection(id: string): Promise<void>;
    deleteStandbySystem(id: string): Promise<void>;
    getAMCPart(id: string): Promise<AMCPart>;
    getAllAMCParts(): Promise<Array<AMCPart>>;
    getAllComplaints(): Promise<Array<Complaint>>;
    getAllComputers(): Promise<Array<Computer>>;
    getAllSections(): Promise<Array<Section>>;
    getAllStandbySystems(): Promise<Array<StandbySystem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComplaint(id: string): Promise<Complaint>;
    getComplaintsByComputer(computerId: string): Promise<Array<Complaint>>;
    getComplaintsBySection(sectionId: string): Promise<Array<Complaint>>;
    getComplaintsByStatus(status: Variant_resolved_open_inProgress): Promise<Array<Complaint>>;
    getComputer(id: string): Promise<Computer>;
    getComputersBySection(sectionId: string): Promise<Array<Computer>>;
    getComputersWithExpiringAMC(days: bigint): Promise<Array<Computer>>;
    getDashboardStats(): Promise<{
        totalStandbySystems: bigint;
        totalComputers: bigint;
        computersWithExpiringAMC: bigint;
        openComplaints: bigint;
        totalSections: bigint;
    }>;
    getExpiringAMCParts(days: bigint): Promise<Array<AMCPart>>;
    getSection(id: string): Promise<Section>;
    getStandbySystem(id: string): Promise<StandbySystem>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAMCPart(part: AMCPart): Promise<void>;
    updateComplaint(complaint: Complaint): Promise<void>;
    updateComputer(computer: Computer): Promise<void>;
    updateSection(section: Section): Promise<void>;
    updateStandbySystem(standbySystem: StandbySystem): Promise<void>;
}
import type { AMCPart as _AMCPart, Complaint as _Complaint, Computer as _Computer, ExternalBlob as _ExternalBlob, StandbySystem as _StandbySystem, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAMCPart(arg0: AMCPart): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAMCPart(to_candid_AMCPart_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAMCPart(to_candid_AMCPart_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createComplaint(arg0: Complaint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createComplaint(to_candid_Complaint_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComplaint(to_candid_Complaint_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createComputer(arg0: Computer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createComputer(await to_candid_Computer_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComputer(await to_candid_Computer_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSection(arg0: Section): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSection(arg0);
            return result;
        }
    }
    async createStandbySystem(arg0: StandbySystem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStandbySystem(to_candid_StandbySystem_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStandbySystem(to_candid_StandbySystem_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAMCPart(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAMCPart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAMCPart(arg0);
            return result;
        }
    }
    async deleteComplaint(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComplaint(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComplaint(arg0);
            return result;
        }
    }
    async deleteComputer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComputer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComputer(arg0);
            return result;
        }
    }
    async deleteSection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSection(arg0);
            return result;
        }
    }
    async deleteStandbySystem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStandbySystem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStandbySystem(arg0);
            return result;
        }
    }
    async getAMCPart(arg0: string): Promise<AMCPart> {
        if (this.processError) {
            try {
                const result = await this.actor.getAMCPart(arg0);
                return from_candid_AMCPart_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAMCPart(arg0);
            return from_candid_AMCPart_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAMCParts(): Promise<Array<AMCPart>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAMCParts();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAMCParts();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllComplaints(): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComplaints();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComplaints();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllComputers(): Promise<Array<Computer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComputers();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComputers();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSections(): Promise<Array<Section>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSections();
            return result;
        }
    }
    async getAllStandbySystems(): Promise<Array<StandbySystem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStandbySystems();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStandbySystems();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaint(arg0: string): Promise<Complaint> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaint(arg0);
                return from_candid_Complaint_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaint(arg0);
            return from_candid_Complaint_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintsByComputer(arg0: string): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintsByComputer(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintsByComputer(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintsBySection(arg0: string): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintsBySection(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintsBySection(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComplaintsByStatus(arg0: Variant_resolved_open_inProgress): Promise<Array<Complaint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplaintsByStatus(to_candid_variant_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplaintsByStatus(to_candid_variant_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComputer(arg0: string): Promise<Computer> {
        if (this.processError) {
            try {
                const result = await this.actor.getComputer(arg0);
                return from_candid_Computer_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComputer(arg0);
            return from_candid_Computer_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComputersBySection(arg0: string): Promise<Array<Computer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComputersBySection(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComputersBySection(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComputersWithExpiringAMC(arg0: bigint): Promise<Array<Computer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComputersWithExpiringAMC(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComputersWithExpiringAMC(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        totalStandbySystems: bigint;
        totalComputers: bigint;
        computersWithExpiringAMC: bigint;
        openComplaints: bigint;
        totalSections: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getExpiringAMCParts(arg0: bigint): Promise<Array<AMCPart>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpiringAMCParts(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpiringAMCParts(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSection(arg0: string): Promise<Section> {
        if (this.processError) {
            try {
                const result = await this.actor.getSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSection(arg0);
            return result;
        }
    }
    async getStandbySystem(arg0: string): Promise<StandbySystem> {
        if (this.processError) {
            try {
                const result = await this.actor.getStandbySystem(arg0);
                return from_candid_StandbySystem_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStandbySystem(arg0);
            return from_candid_StandbySystem_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAMCPart(arg0: AMCPart): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAMCPart(to_candid_AMCPart_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAMCPart(to_candid_AMCPart_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateComplaint(arg0: Complaint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplaint(to_candid_Complaint_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplaint(to_candid_Complaint_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateComputer(arg0: Computer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComputer(await to_candid_Computer_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComputer(await to_candid_Computer_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSection(arg0: Section): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSection(arg0);
            return result;
        }
    }
    async updateStandbySystem(arg0: StandbySystem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStandbySystem(to_candid_StandbySystem_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStandbySystem(to_candid_StandbySystem_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AMCPart_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AMCPart): AMCPart {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Complaint_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Complaint): Complaint {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Computer_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Computer): Promise<Computer> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_StandbySystem_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StandbySystem): StandbySystem {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    associatedComputerId: [] | [string];
    purchaseDate: bigint;
    associatedSectionId: [] | [string];
    partNumber: string;
    supplier: string;
    createdAt: bigint;
    partName: string;
    notes: string;
    warrantyExpiry: [] | [bigint];
    quantity: bigint;
}): {
    id: string;
    associatedComputerId?: string;
    purchaseDate: bigint;
    associatedSectionId?: string;
    partNumber: string;
    supplier: string;
    createdAt: bigint;
    partName: string;
    notes: string;
    warrantyExpiry?: bigint;
    quantity: bigint;
} {
    return {
        id: value.id,
        associatedComputerId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.associatedComputerId)),
        purchaseDate: value.purchaseDate,
        associatedSectionId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.associatedSectionId)),
        partNumber: value.partNumber,
        supplier: value.supplier,
        createdAt: value.createdAt,
        partName: value.partName,
        notes: value.notes,
        warrantyExpiry: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.warrantyExpiry)),
        quantity: value.quantity
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        resolved: null;
    } | {
        open: null;
    } | {
        inProgress: null;
    };
    computerId: [] | [string];
    createdAt: bigint;
    description: string;
    sectionId: [] | [string];
    reportedBy: string;
    priority: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
    resolvedAt: [] | [bigint];
}): {
    id: string;
    status: Variant_resolved_open_inProgress;
    computerId?: string;
    createdAt: bigint;
    description: string;
    sectionId?: string;
    reportedBy: string;
    priority: Variant_low_high_medium;
    resolvedAt?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n32(_uploadFile, _downloadFile, value.status),
        computerId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.computerId)),
        createdAt: value.createdAt,
        description: value.description,
        sectionId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.sectionId)),
        reportedBy: value.reportedBy,
        priority: from_candid_variant_n33(_uploadFile, _downloadFile, value.priority),
        resolvedAt: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.resolvedAt))
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        active: null;
    } | {
        standby: null;
    } | {
        retired: null;
    };
    model: string;
    datasheetBlob: [] | [_ExternalBlob];
    purchaseDate: bigint;
    createdAt: bigint;
    currentUser: string;
    sectionId: string;
    serialNumber: string;
    notes: string;
    brand: string;
    amcEndDate: bigint;
    amcStartDate: bigint;
    seatNumber: string;
}): Promise<{
    id: string;
    status: Variant_active_standby_retired;
    model: string;
    datasheetBlob?: ExternalBlob;
    purchaseDate: bigint;
    createdAt: bigint;
    currentUser: string;
    sectionId: string;
    serialNumber: string;
    notes: string;
    brand: string;
    amcEndDate: bigint;
    amcStartDate: bigint;
    seatNumber: string;
}> {
    return {
        id: value.id,
        status: from_candid_variant_n37(_uploadFile, _downloadFile, value.status),
        model: value.model,
        datasheetBlob: record_opt_to_undefined(await from_candid_opt_n38(_uploadFile, _downloadFile, value.datasheetBlob)),
        purchaseDate: value.purchaseDate,
        createdAt: value.createdAt,
        currentUser: value.currentUser,
        sectionId: value.sectionId,
        serialNumber: value.serialNumber,
        notes: value.notes,
        brand: value.brand,
        amcEndDate: value.amcEndDate,
        amcStartDate: value.amcStartDate,
        seatNumber: value.seatNumber
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        available: null;
    } | {
        inUse: null;
    } | {
        retired: null;
    };
    model: string;
    createdAt: bigint;
    assignedSectionId: [] | [string];
    serialNumber: string;
    notes: string;
    brand: string;
    condition: {
        fair: null;
    } | {
        good: null;
    } | {
        poor: null;
    };
}): {
    id: string;
    status: Variant_available_inUse_retired;
    model: string;
    createdAt: bigint;
    assignedSectionId?: string;
    serialNumber: string;
    notes: string;
    brand: string;
    condition: Variant_fair_good_poor;
} {
    return {
        id: value.id,
        status: from_candid_variant_n43(_uploadFile, _downloadFile, value.status),
        model: value.model,
        createdAt: value.createdAt,
        assignedSectionId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.assignedSectionId)),
        serialNumber: value.serialNumber,
        notes: value.notes,
        brand: value.brand,
        condition: from_candid_variant_n44(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    open: null;
} | {
    inProgress: null;
}): Variant_resolved_open_inProgress {
    return "resolved" in value ? Variant_resolved_open_inProgress.resolved : "open" in value ? Variant_resolved_open_inProgress.open : "inProgress" in value ? Variant_resolved_open_inProgress.inProgress : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Variant_low_high_medium {
    return "low" in value ? Variant_low_high_medium.low : "high" in value ? Variant_low_high_medium.high : "medium" in value ? Variant_low_high_medium.medium : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    standby: null;
} | {
    retired: null;
}): Variant_active_standby_retired {
    return "active" in value ? Variant_active_standby_retired.active : "standby" in value ? Variant_active_standby_retired.standby : "retired" in value ? Variant_active_standby_retired.retired : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    available: null;
} | {
    inUse: null;
} | {
    retired: null;
}): Variant_available_inUse_retired {
    return "available" in value ? Variant_available_inUse_retired.available : "inUse" in value ? Variant_available_inUse_retired.inUse : "retired" in value ? Variant_available_inUse_retired.retired : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
}): Variant_fair_good_poor {
    return "fair" in value ? Variant_fair_good_poor.fair : "good" in value ? Variant_fair_good_poor.good : "poor" in value ? Variant_fair_good_poor.poor : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AMCPart>): Array<AMCPart> {
    return value.map((x)=>from_candid_AMCPart_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Complaint>): Array<Complaint> {
    return value.map((x)=>from_candid_Complaint_n30(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Computer>): Promise<Array<Computer>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Computer_n35(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StandbySystem>): Array<StandbySystem> {
    return value.map((x)=>from_candid_StandbySystem_n41(_uploadFile, _downloadFile, x));
}
function to_candid_AMCPart_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AMCPart): _AMCPart {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Complaint_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Complaint): _Complaint {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_Computer_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Computer): Promise<_Computer> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_StandbySystem_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StandbySystem): _StandbySystem {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    associatedComputerId?: string;
    purchaseDate: bigint;
    associatedSectionId?: string;
    partNumber: string;
    supplier: string;
    createdAt: bigint;
    partName: string;
    notes: string;
    warrantyExpiry?: bigint;
    quantity: bigint;
}): {
    id: string;
    associatedComputerId: [] | [string];
    purchaseDate: bigint;
    associatedSectionId: [] | [string];
    partNumber: string;
    supplier: string;
    createdAt: bigint;
    partName: string;
    notes: string;
    warrantyExpiry: [] | [bigint];
    quantity: bigint;
} {
    return {
        id: value.id,
        associatedComputerId: value.associatedComputerId ? candid_some(value.associatedComputerId) : candid_none(),
        purchaseDate: value.purchaseDate,
        associatedSectionId: value.associatedSectionId ? candid_some(value.associatedSectionId) : candid_none(),
        partNumber: value.partNumber,
        supplier: value.supplier,
        createdAt: value.createdAt,
        partName: value.partName,
        notes: value.notes,
        warrantyExpiry: value.warrantyExpiry ? candid_some(value.warrantyExpiry) : candid_none(),
        quantity: value.quantity
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_resolved_open_inProgress;
    computerId?: string;
    createdAt: bigint;
    description: string;
    sectionId?: string;
    reportedBy: string;
    priority: Variant_low_high_medium;
    resolvedAt?: bigint;
}): {
    id: string;
    status: {
        resolved: null;
    } | {
        open: null;
    } | {
        inProgress: null;
    };
    computerId: [] | [string];
    createdAt: bigint;
    description: string;
    sectionId: [] | [string];
    reportedBy: string;
    priority: {
        low: null;
    } | {
        high: null;
    } | {
        medium: null;
    };
    resolvedAt: [] | [bigint];
} {
    return {
        id: value.id,
        status: to_candid_variant_n14(_uploadFile, _downloadFile, value.status),
        computerId: value.computerId ? candid_some(value.computerId) : candid_none(),
        createdAt: value.createdAt,
        description: value.description,
        sectionId: value.sectionId ? candid_some(value.sectionId) : candid_none(),
        reportedBy: value.reportedBy,
        priority: to_candid_variant_n15(_uploadFile, _downloadFile, value.priority),
        resolvedAt: value.resolvedAt ? candid_some(value.resolvedAt) : candid_none()
    };
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_active_standby_retired;
    model: string;
    datasheetBlob?: ExternalBlob;
    purchaseDate: bigint;
    createdAt: bigint;
    currentUser: string;
    sectionId: string;
    serialNumber: string;
    notes: string;
    brand: string;
    amcEndDate: bigint;
    amcStartDate: bigint;
    seatNumber: string;
}): Promise<{
    id: string;
    status: {
        active: null;
    } | {
        standby: null;
    } | {
        retired: null;
    };
    model: string;
    datasheetBlob: [] | [_ExternalBlob];
    purchaseDate: bigint;
    createdAt: bigint;
    currentUser: string;
    sectionId: string;
    serialNumber: string;
    notes: string;
    brand: string;
    amcEndDate: bigint;
    amcStartDate: bigint;
    seatNumber: string;
}> {
    return {
        id: value.id,
        status: to_candid_variant_n18(_uploadFile, _downloadFile, value.status),
        model: value.model,
        datasheetBlob: value.datasheetBlob ? candid_some(await to_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.datasheetBlob)) : candid_none(),
        purchaseDate: value.purchaseDate,
        createdAt: value.createdAt,
        currentUser: value.currentUser,
        sectionId: value.sectionId,
        serialNumber: value.serialNumber,
        notes: value.notes,
        brand: value.brand,
        amcEndDate: value.amcEndDate,
        amcStartDate: value.amcStartDate,
        seatNumber: value.seatNumber
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_available_inUse_retired;
    model: string;
    createdAt: bigint;
    assignedSectionId?: string;
    serialNumber: string;
    notes: string;
    brand: string;
    condition: Variant_fair_good_poor;
}): {
    id: string;
    status: {
        available: null;
    } | {
        inUse: null;
    } | {
        retired: null;
    };
    model: string;
    createdAt: bigint;
    assignedSectionId: [] | [string];
    serialNumber: string;
    notes: string;
    brand: string;
    condition: {
        fair: null;
    } | {
        good: null;
    } | {
        poor: null;
    };
} {
    return {
        id: value.id,
        status: to_candid_variant_n22(_uploadFile, _downloadFile, value.status),
        model: value.model,
        createdAt: value.createdAt,
        assignedSectionId: value.assignedSectionId ? candid_some(value.assignedSectionId) : candid_none(),
        serialNumber: value.serialNumber,
        notes: value.notes,
        brand: value.brand,
        condition: to_candid_variant_n23(_uploadFile, _downloadFile, value.condition)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_resolved_open_inProgress): {
    resolved: null;
} | {
    open: null;
} | {
    inProgress: null;
} {
    return value == Variant_resolved_open_inProgress.resolved ? {
        resolved: null
    } : value == Variant_resolved_open_inProgress.open ? {
        open: null
    } : value == Variant_resolved_open_inProgress.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_low_high_medium): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Variant_low_high_medium.low ? {
        low: null
    } : value == Variant_low_high_medium.high ? {
        high: null
    } : value == Variant_low_high_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_active_standby_retired): {
    active: null;
} | {
    standby: null;
} | {
    retired: null;
} {
    return value == Variant_active_standby_retired.active ? {
        active: null
    } : value == Variant_active_standby_retired.standby ? {
        standby: null
    } : value == Variant_active_standby_retired.retired ? {
        retired: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_available_inUse_retired): {
    available: null;
} | {
    inUse: null;
} | {
    retired: null;
} {
    return value == Variant_available_inUse_retired.available ? {
        available: null
    } : value == Variant_available_inUse_retired.inUse ? {
        inUse: null
    } : value == Variant_available_inUse_retired.retired ? {
        retired: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_fair_good_poor): {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
} {
    return value == Variant_fair_good_poor.fair ? {
        fair: null
    } : value == Variant_fair_good_poor.good ? {
        good: null
    } : value == Variant_fair_good_poor.poor ? {
        poor: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
